### ISSUE TITLE
yaml: SystemError: unable to find to find module: PyQt5.QtGui

### ISSUE THREAD

**Issue by sarahzhouUestc** [afunTW/pyqt5-video-labeling#1]
@afunTW hello. I encouter an error when executing main.py, the error message as follows:

![image](https://user-images.githubusercontent.com/19327575/50398807-72eb2980-07b5-11e9-9810-9fcc811692d5.png)

**but I can import PyQt5.QtGui successfully in Python Console:**

![image](https://user-images.githubusercontent.com/19327575/50398699-96fa3b00-07b4-11e9-9ec6-8dc80233fa5d.png)

**I don't know why yaml can't find the PyQt5.QtGui module, could you help me? Thanks a lot :)**

**Comment by afunTW** [comment]
First of all, I used the `pipenv` to set up the dependencies. If you follow the instruction 
```bash
cd pyqt5-video-labeling
pipenv shell && pipenv sync
``` 
and simply test the yaml loading
```python
import yaml
with open('config.yaml', 'r') as f:
  config = yaml.load(f)
print(config)
```
that should be as same environment as mine. Otherwise, I will suggest you check from the very begin of python and package path.

![image](https://user-images.githubusercontent.com/4820492/50403713-dbe59800-07db-11e9-9361-6859a608c5b3.png)

**Comment by afunTW** [comment]
Since the issue have the proper solution and no feedback in few days, closed this issue in temporary
